### ISSUE TITLE
Custom component not working 

### ISSUE THREAD

**Issue by shrirenjith** [mattiasflodin/home-assistant-deconz#1]
I couldn't get this to work. I tried the documented steps and it seems like the plugin is failing to import the libdeconz  library . It is not able to find it .  It have the libdeconz.py in the  config/deps .

**Comment by mattiasflodin** [comment]
Hi,

This project has been discontinued since it is rendered obsolete by the built-in support in Home Assistant. Please refer to the documentation at https://www.home-assistant.io/components/deconz/
